sudo: required
services:
  - docker

before_install:
  - docker build -t rajaraghav/reactdocker -f Dockerfile.dev .

script:
  - docker run rajaraghav/reactdocker npm test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "reactDocker"
  env: "reactDocker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-263467945630"
  bucket_path: "reactDocker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
